//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Load_Tags_From_DB_Using_Angular_JS_In_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTag
    {
        public int tagId { get; set; }
        public string tagName { get; set; }
        public string tagDescription { get; set; }
    }
}
